# Generated by Django 3.1.7 on 2021-03-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210307_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
