# Generated by Django 3.1.7 on 2021-03-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210307_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
    ]
