# Generated by Django 3.1.7 on 2021-03-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='BugCategory',
        ),
    ]
